service: authorization-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

plugins:
- serverless-esbuild
- serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false
    platform: 'node'
    target: 'node16'

functions:
  basicAuthorizer:
    handler: index.basicAuthorizer
    events:
      - http:
          path: import
          method: get
          cors: true
